### PR TITLE
DIGEQ-125 Travis CI deployments

### PR DESCRIPTION
**Pull request by warren-methods**
**What**
Allows travis to deploy into terraform

**How to test**
1. Trigger a travis build 
2. When complete browse to: https://travis-ons-eq-author.herokuapp.com/login/?next=/surveys/

**Who can review**
Anyone apart from @dhilton and @warren-methods

### CODE REVIEW

**Comment by dhilton** [comment]
We hit a slight gotcha in that if terraform **doesn't** have a local statefile it assumes there is no state (even though we setup remote state - annoying!)

More explanation in this blog post: http://karlcode.owtelse.com/blog/2015/09/01/working-with-terraform-remote-statefile/

 So two options:

1) Don't worry - we just wipe slate clean everytime - structure the CI test to create an environment, in future run a set of smoke tests and then destroy it.
2) Grab the state file from S3 before we run terraform, performing a pre-deploy sync. 

My personal preference on this is perhaps to go with (1) and then use a different method to deploy a nightlies environment for PO sign-off and review, with an adhoc deployment of a stakeholder demo environment with the statefile stored in another S3 bucket. That way we square off both of the allocated stories.

Thoughts? In scenario 1 this PR looks good with a slight reordering of how the Travis job runs. This is more akin to a traditional CI environment and would allow us to layer in Sauce labs automated browser testing against that environment as well as infrataster based smoke tests.

**Comment by collisdigital** [comment]
@dhilton can we use "terraform remote pull" ? https://www.terraform.io/docs/commands/remote-pull.html

**Comment by warren-methods** [comment]
Added 'terraform remote pull command'

**Comment by warren-methods** [comment]
Rebased

**Comment by dhilton** [comment]
Chatted to @warren-methods and rest of team - happy to merge this now :+1:

**Pull request merged**
