### PR TITLE
terraform 0.7.0 info added to README

### PR DESCRIPTION
**Pull request by jjeane**
### What is the context of this PR?

Updated README to include info for terraform 0.7.0
### How to review

Get terraform 0.7.0 
Make sure you can deploy by following steps
- [ ] Do all commits have sensible commit messages?
- [ ] Is there documentation or is the code self-describing?
### Who worked on the PR

@jjeane

### CODE REVIEW

**Comment by warrenbailey** [comment]
We probably should upgrade everything to v0.7.0 so I think it makes sense to update the terraform.tfvars.example file too.

**Comment by jjeane** [comment]
Shall I switch around the README to include the info for 0.6.xx versions, or just omit completely?

**Comment by warrenbailey** [comment]
I think we should go to the latest version, so maybe just omit the 0.6.xxx versions

**Comment by warrenbailey** [comment]
LGTM 👍

**Pull request merged**
