### PR TITLE
Restrict SSH access and document higher security

### PR DESCRIPTION
**Pull request by dhilton**
**What**
This PR removes ssh access to the Elastic Beanstalk application surveys and
documents how to remove access to the RabbitMQ servers once provisioning has
succeeded.

**How to test**
1. Deploy this branch to dev AWS account.
2. Try to connect to Elastic Beanstalk servers as listed in console using telnet on port 22
3. Follow the instructions in the README.md to remove the security group rules and public addresses for the rabbitmq machines.

**Who can test**

Anyone but @dhilton

### CODE REVIEW

**Comment by weapdiv-david** [comment]
I'm having permission issues with this also.

**Comment by dhilton** [comment]
Rebasing after merge of @warrenbailey PR and conversation with @weapdiv-david aroumd ec2 instance size issues.

**Comment by warrenbailey** [comment]
As discussed, we'll add a security group specifically  for rabbit mq and then remove that once it's deployed.

**Comment by warrenbailey** [comment]
Excellent, all works :+1:

**Pull request merged**
