### PR TITLE
Remove unused variable database_cidrs

### PR DESCRIPTION
**Pull request by jonnyshaw89**
### What is the context of this PR?
We don't need this variable so we should remove the need for it

### How to review
Does it work without it?

### CODE REVIEW

**Comment by shahi645** [comment]
The changes aren't related to this, but only seem to get this on your branch:

```
Error: Error running plan: 1 error(s) occurred:

* module.survey-runner-routing.aws_route_table_association.private: aws_route_table_association.private: value of 'count' cannot be computed
```

**Review by shahi645 — CHANGES_REQUESTED** [review]
The changes aren't related to this, but only seem to get this on your branch:

```
Error: Error running plan: 1 error(s) occurred:

* module.survey-runner-routing.aws_route_table_association.private: aws_route_table_association.private: value of 'count' cannot be computed
```

**Comment by jonnyshaw89** [comment]
@shahi645 fixed this

**Review by shahi645 — APPROVED** [review]
Works for me now 👍

**Review by kierenbeckett — APPROVED** [review]

**Review by dwyeradam — APPROVED** [review]

**Pull request merged**
